chore(deps): update dependency eslint to v8.56.0 (#384)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [eslint](https://eslint.org)
([source](https://togithub.com/eslint/eslint)) | [`8.52.0` ->
`8.56.0`](https://renovatebot.com/diffs/npm/eslint/8.52.0/8.56.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint/8.52.0/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/8.52.0/8.56.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>eslint/eslint (eslint)</summary>

### [`v8.56.0`](https://togithub.com/eslint/eslint/releases/tag/v8.56.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.55.0...v8.56.0)

##### Features

-
[`0dd9704`](https://togithub.com/eslint/eslint/commit/0dd9704c4751e1cd02039f7d6485fee09bbccbf6)
feat: Support custom severity when reporting unused disable directives
([#&#8203;17212](https://togithub.com/eslint/eslint/issues/17212))
(Bryan Mishkin)
-
[`31a7e3f`](https://togithub.com/eslint/eslint/commit/31a7e3fde491e36496b54e8905c766b31162d776)
feat: fix no-restricted-properties false negatives with unknown objects
([#&#8203;17818](https://togithub.com/eslint/eslint/issues/17818)) (Arka
Pratim Chaudhuri)

##### Bug Fixes

-
[`7d5e5f6`](https://togithub.com/eslint/eslint/commit/7d5e5f68849ae80caec0fc96ecceebccd348deec)
fix: `TypeError: fs.exists is not a function` on read-only file system
([#&#8203;17846](https://togithub.com/eslint/eslint/issues/17846))
(Francesco Trotta)
-
[`74739c8`](https://togithub.com/eslint/eslint/commit/74739c849bbb6547b0e555ed8bb2ba1cbe0fdce4)
fix: suggestion with invalid syntax in no-promise-executor-return rule
([#&#8203;17812](https://togithub.com/eslint/eslint/issues/17812))
(Bryan Mishkin)

##### Documentation

-
[`9007719`](https://togithub.com/eslint/eslint/commit/90077199fe519953f9af8664bf947db4e4958514)
docs: update link in ways-to-extend.md
([#&#8203;17839](https://togithub.com/eslint/eslint/issues/17839)) (Amel
SELMANE)
-
[`3a22236`](https://togithub.com/eslint/eslint/commit/3a22236f8d10af8a5bcafe56092651d3d681c99d)
docs: Update README (GitHub Actions Bot)
-
[`54c3ca6`](https://togithub.com/eslint/eslint/commit/54c3ca6f2dcd2a7afd53f42fc32055a25587259e)
docs: fix migration-guide example
([#&#8203;17829](https://togithub.com/eslint/eslint/issues/17829))
(Tanuj Kanti)
-
[`4391b71`](https://togithub.com/eslint/eslint/commit/4391b71e62b15e54b0493f0dce1ea053ebbc0689)
docs: check config comments in rule examples
([#&#8203;17815](https://togithub.com/eslint/eslint/issues/17815))
(Francesco Trotta)
-
[`fd28363`](https://togithub.com/eslint/eslint/commit/fd2836342c2be4751b05fe0ba7cece17d1edecc8)
docs: remove mention about ESLint stylistic rules in readme
([#&#8203;17810](https://togithub.com/eslint/eslint/issues/17810))
(Zwyx)
-
[`48ed5a6`](https://togithub.com/eslint/eslint/commit/48ed5a6dad478a14d3e823f137455c523f373e0b)
docs: Update README (GitHub Actions Bot)

##### Chores

-
[`ba6af85`](https://togithub.com/eslint/eslint/commit/ba6af85c7d8ba55d37f8663aee949d148e441c1a)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).56.0
([#&#8203;17864](https://togithub.com/eslint/eslint/issues/17864))
(Milos Djermanovic)
-
[`60a531a`](https://togithub.com/eslint/eslint/commit/60a531a9c0811ddf718e26b9136e133f580b6c36)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`ba87a06`](https://togithub.com/eslint/eslint/commit/ba87a0651a65b52c3ac442b512dd9f4c2b4c5f57)
chore: update dependency markdownlint to ^0.32.0
([#&#8203;17783](https://togithub.com/eslint/eslint/issues/17783))
(renovate\[bot])
-
[`9271d10`](https://togithub.com/eslint/eslint/commit/9271d10d9eabeafb0129a090f29191bfd14273c0)
chore: add GitHub issue template for docs issues
([#&#8203;17845](https://togithub.com/eslint/eslint/issues/17845)) (Josh
Goldberg ✨)
-
[`70a686b`](https://togithub.com/eslint/eslint/commit/70a686b3c1feac5eca98bbff9bd67175f550d5db)
chore: Convert rule tests to FlatRuleTester
([#&#8203;17819](https://togithub.com/eslint/eslint/issues/17819))
(Nicholas C. Zakas)
-
[`f3a599d`](https://togithub.com/eslint/eslint/commit/f3a599d34c7080fc0b2c9a60b5e54dc98c22867c)
chore: upgrade eslint-plugin-unicorn to v49.0.0
([#&#8203;17837](https://togithub.com/eslint/eslint/issues/17837)) (唯然)
-
[`905d4b7`](https://togithub.com/eslint/eslint/commit/905d4b75ab2df42aba30622cee0f66b511397e2c)
chore: upgrade eslint-plugin-eslint-plugin v5.2.1
([#&#8203;17838](https://togithub.com/eslint/eslint/issues/17838)) (唯然)
-
[`4d7c3ce`](https://togithub.com/eslint/eslint/commit/4d7c3ce246e6b499f472342ef59496a47cc033d6)
chore: update eslint-plugin-n v16.4.0
([#&#8203;17836](https://togithub.com/eslint/eslint/issues/17836)) (唯然)
-
[`fd0c60c`](https://togithub.com/eslint/eslint/commit/fd0c60c3be1f213e5a6d69d8a3248e963619e155)
ci: unpin Node.js 21.2.0
([#&#8203;17821](https://togithub.com/eslint/eslint/issues/17821))
(Francesco Trotta)

### [`v8.55.0`](https://togithub.com/eslint/eslint/releases/tag/v8.55.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.54.0...v8.55.0)

#### Features

-
[`8c9e6c1`](https://togithub.com/eslint/eslint/commit/8c9e6c100a6eb69da292463293b3b48cff911a01)
feat: importNamePattern option in no-restricted-imports
([#&#8203;17721](https://togithub.com/eslint/eslint/issues/17721))
(Tanuj Kanti)

#### Documentation

-
[`83ece2a`](https://togithub.com/eslint/eslint/commit/83ece2afc2dc6c49efe82678663fe4cba590c0e5)
docs: fix typo `--rules` -> `--rule`
([#&#8203;17806](https://togithub.com/eslint/eslint/issues/17806))
(OKURA Masafumi)
-
[`fffca5c`](https://togithub.com/eslint/eslint/commit/fffca5c362bcd205dbf79d1bb52834f8a98fc6bd)
docs: remove "Open in Playground" buttons for removed rules
([#&#8203;17791](https://togithub.com/eslint/eslint/issues/17791))
(Francesco Trotta)
-
[`a6d9442`](https://togithub.com/eslint/eslint/commit/a6d9442a9ab34d5d19f78d8c8fd0767a1237bfe3)
docs: fix correct/incorrect examples of rules
([#&#8203;17789](https://togithub.com/eslint/eslint/issues/17789))
(Tanuj Kanti)
-
[`383e999`](https://togithub.com/eslint/eslint/commit/383e99928d7ce649ec9030c9856b03fbac0c3501)
docs: update and fix examples for `no-unused-vars`
([#&#8203;17788](https://togithub.com/eslint/eslint/issues/17788))
(Tanuj Kanti)
-
[`5a8efd5`](https://togithub.com/eslint/eslint/commit/5a8efd5b7ad13eb320a1f468d1d4ab3c8ab99214)
docs: add specific stylistic rule for each deprecated rule
([#&#8203;17778](https://togithub.com/eslint/eslint/issues/17778))
(Etienne)

#### Chores

-
[`eb8950c`](https://togithub.com/eslint/eslint/commit/eb8950c3b811c9163b9aae23af8b6266ad98b295)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).55.0
([#&#8203;17811](https://togithub.com/eslint/eslint/issues/17811))
(Milos Djermanovic)
-
[`93df384`](https://togithub.com/eslint/eslint/commit/93df3849a7a25ebe0502000bf0bfb80a6613a5ae)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`fe4b954`](https://togithub.com/eslint/eslint/commit/fe4b9545a83e9aca7ba4bb77bc9c868d57de777f)
chore: upgrade
[@&#8203;eslint/eslintrc](https://togithub.com/eslint/eslintrc)[@&#8203;2](https://togithub.com/2).1.4
([#&#8203;17799](https://togithub.com/eslint/eslint/issues/17799))
(Milos Djermanovic)
-
[`bd8911d`](https://togithub.com/eslint/eslint/commit/bd8911db85c7a1127543c9212c8cea47a5cb687d)
ci: pin Node.js 21.2.0
([#&#8203;17809](https://togithub.com/eslint/eslint/issues/17809))
(Milos Djermanovic)
-
[`b29a16b`](https://togithub.com/eslint/eslint/commit/b29a16b22f234f6134475efb6c7be5ac946556ee)
chore: fix several `cli` tests to run in the intended flat config mode
([#&#8203;17797](https://togithub.com/eslint/eslint/issues/17797))
(Milos Djermanovic)
-
[`de165c1`](https://togithub.com/eslint/eslint/commit/de165c108203c6703516ac651f5b4cac5b241804)
chore: remove unused config-extends fixtures
([#&#8203;17781](https://togithub.com/eslint/eslint/issues/17781))
(Milos Djermanovic)
-
[`d4304b8`](https://togithub.com/eslint/eslint/commit/d4304b8b66eac870ffbf4840d84add8a123b25fc)
chore: remove formatting/stylistic rules from new rule templates
([#&#8203;17780](https://togithub.com/eslint/eslint/issues/17780))
(Francesco Trotta)
-
[`21024fe`](https://togithub.com/eslint/eslint/commit/21024fe2029420b413bed11d23761c87e9a02a1a)
chore: check rule examples for syntax errors
([#&#8203;17718](https://togithub.com/eslint/eslint/issues/17718))
(Francesco Trotta)

### [`v8.54.0`](https://togithub.com/eslint/eslint/releases/tag/v8.54.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.53.0...v8.54.0)

#### Features

-
[`a7a883b`](https://togithub.com/eslint/eslint/commit/a7a883bd6ba4f140b60cbbb2be5b53d750f6c8db)
feat: for-direction rule add check for condition in reverse order
([#&#8203;17755](https://togithub.com/eslint/eslint/issues/17755))
(Angelo Annunziata)
-
[`1452dc9`](https://togithub.com/eslint/eslint/commit/1452dc9f12c45c05d7c569f737221f0d988ecef1)
feat: Add suggestions to no-console
([#&#8203;17680](https://togithub.com/eslint/eslint/issues/17680)) (Joel
Mathew Koshy)
-
[`21ebf8a`](https://togithub.com/eslint/eslint/commit/21ebf8a811be9f4b009cf70a10be5062d4fdc736)
feat: update `no-array-constructor` rule
([#&#8203;17711](https://togithub.com/eslint/eslint/issues/17711))
(Francesco Trotta)

#### Bug Fixes

-
[`98926e6`](https://togithub.com/eslint/eslint/commit/98926e6e7323e5dd12a9f016cb558144296665af)
fix: Ensure that extra data is not accidentally stored in the cache file
([#&#8203;17760](https://togithub.com/eslint/eslint/issues/17760))
(Milos Djermanovic)
-
[`e8cf9f6`](https://togithub.com/eslint/eslint/commit/e8cf9f6a524332293f8b2c90a2db4a532e47d919)
fix: Make dark scroll bar in dark theme
([#&#8203;17753](https://togithub.com/eslint/eslint/issues/17753))
(Pavel)
-
[`3cbeaad`](https://togithub.com/eslint/eslint/commit/3cbeaad7b943c153937ce34365cec2c406f2b98b)
fix: Use `cwd` constructor option as config `basePath` in Linter
([#&#8203;17705](https://togithub.com/eslint/eslint/issues/17705))
(Milos Djermanovic)

#### Documentation

-
[`becfdd3`](https://togithub.com/eslint/eslint/commit/becfdd39b25d795e56c9a13eb3e77af6b9c86e8a)
docs: Make clear when rules are removed
([#&#8203;17728](https://togithub.com/eslint/eslint/issues/17728))
(Nicholas C. Zakas)
-
[`05d6e99`](https://togithub.com/eslint/eslint/commit/05d6e99153ed6d94eb30f46c57609371918a41f3)
docs: update "Submit a Pull Request" page
([#&#8203;17712](https://togithub.com/eslint/eslint/issues/17712))
(Francesco Trotta)
-
[`eb2279e`](https://togithub.com/eslint/eslint/commit/eb2279e5148cee8fdea7dae614f4f8af7a2d06c3)
docs: display info about deprecated rules
([#&#8203;17749](https://togithub.com/eslint/eslint/issues/17749))
(Percy Ma)
-
[`d245326`](https://togithub.com/eslint/eslint/commit/d24532601e64714ac5d08507e05aa5c14ecd1d5a)
docs: Correct working in migrating plugin docs
([#&#8203;17722](https://togithub.com/eslint/eslint/issues/17722))
(Filip Tammergård)

#### Chores

-
[`d644de9`](https://togithub.com/eslint/eslint/commit/d644de9a4b593b565617303a095bc9aa69e7b768)
chore: upgrade
[@&#8203;eslint/js](https://togithub.com/eslint/js)[@&#8203;8](https://togithub.com/8).54.0
([#&#8203;17773](https://togithub.com/eslint/eslint/issues/17773))
(Milos Djermanovic)
-
[`1e6e314`](https://togithub.com/eslint/eslint/commit/1e6e31415cc429a3a9fc64b2ec03df0e0ec0c91b)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (Jenkins)
-
[`6fb8805`](https://togithub.com/eslint/eslint/commit/6fb8805310afe7476d6c404f172177a6d15fcf11)
chore: Fixed grammar in issue_templates/rule_change
([#&#8203;17770](https://togithub.com/eslint/eslint/issues/17770)) (Joel
Mathew Koshy)
-
[`85db724`](https://togithub.com/eslint/eslint/commit/85db7243ddb8706ed60ab64a7ddf604d0d7de493)
chore: upgrade `markdownlint` to 0.31.1
([#&#8203;17754](https://togithub.com/eslint/eslint/issues/17754))
(Nitin Kumar)
-
[`6d470d2`](https://togithub.com/eslint/eslint/commit/6d470d2e74535761bd56dcb1c021b463ef9e8a9c)
chore: update dependency recast to ^0.23.0
([#&#8203;17736](https://togithub.com/eslint/eslint/issues/17736))
(renovate\[bot])
-
[`b7121b5`](https://togithub.com/eslint/eslint/commit/b7121b590d578c9c9b38ee481313317f30e54817)
chore: update dependency markdownlint-cli to ^0.37.0
([#&#8203;17735](https://togithub.com/eslint/eslint/issues/17735))
(renovate\[bot])
-
[`633b9a1`](https://togithub.com/eslint/eslint/commit/633b9a19752b6a22ab4d6c824f27a75ac0e4151b)
chore: update dependency regenerator-runtime to ^0.14.0
([#&#8203;17739](https://togithub.com/eslint/eslint/issues/17739))
(renovate\[bot])
-
[`acac16f`](https://togithub.com/eslint/eslint/commit/acac16fdf8540f7ba86cf637e3c1b253bd35a268)
chore: update dependency vite-plugin-commonjs to ^0.10.0
([#&#8203;17740](https://togithub.com/eslint/eslint/issues/17740))
(renovate\[bot])
-
[`ba8ca7e`](https://togithub.com/eslint/eslint/commit/ba8ca7e3debcba68ee7015b9221cf5acd7870206)
chore: add .github/renovate.json5
([#&#8203;17567](https://togithub.com/eslint/eslint/issues/17567)) (Josh
Goldberg ✨)

### [`v8.53.0`](https://togithub.com/eslint/eslint/releases/tag/v8.53.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.52.0...v8.53.0)

#### Features

-
[`528e1c0`](https://togithub.com/eslint/eslint/commit/528e1c00dc2aa8636e5b706c4270dc655cfa17e3)
feat: Deprecate formatting rules
([#&#8203;17696](https://togithub.com/eslint/eslint/issues/17696))
(Nicholas C. Zakas)
-
[`c0b11dd`](https://togithub.com/eslint/eslint/commit/c0b11ddb9f8aacc64c3933b9f278939aa7bea481)
feat: Add suggestions for no-prototype-builtins
([#&#8203;17677](https://togithub.com/eslint/eslint/issues/17677))
(Yonathan Randolph)

#### Bug Fixes

-
[`1ad6257`](https://togithub.com/eslint/eslint/commit/1ad6257744d63281235fcc33288394b1d69b34ce)
fix: ensure that exit code for fatal errors is not overwritten
([#&#8203;17683](https://togithub.com/eslint/eslint/issues/17683))
(Milos Djermanovic)
-
[`b329ea7`](https://togithub.com/eslint/eslint/commit/b329ea748dff45f11c7e218208244dc24fcb5c8f)
fix: add `;` after JSX nodes in `no-object-constructor` autofix
([#&#8203;17672](https://togithub.com/eslint/eslint/issues/17672))
(Francesco Trotta)

#### Documentation

-
[`ab8c60d`](https://togithub.com/eslint/eslint/commit/ab8c60d4f859cec787b5a12f7271b40e666235f5)
docs: change position of return to top button
([#&#8203;17688](https://togithub.com/eslint/eslint/issues/17688))
(Tanuj Kanti)
-
[`4fc44c0`](https://togithub.com/eslint/eslint/commit/4fc44c0b8c5dca466bffdfe01dfd80794d7762b7)
docs: update twitter icon to new X icon
([#&#8203;17687](https://togithub.com/eslint/eslint/issues/17687))
(Tanuj Kanti)
-
[`4164b2c`](https://togithub.com/eslint/eslint/commit/4164b2ceec89726b18ea0b0e34fab05735d55a09)
docs: Update README (GitHub Actions Bot)
-
[`8651895`](https://togithub.com/eslint/eslint/commit/8651895ca7ae15e13d74c8be67d9eebd63a7ce1f)
docs: Fix tabs in rule examples
([#&#8203;17653](https://togithub.com/eslint/eslint/issues/17653))
(Francesco Trotta)
-
[`3aec1c5`](https://togithub.com/eslint/eslint/commit/3aec1c55ba2c6d2833e1c0afe0a58f0cc6bbc0a4)
docs: explained rule fixers and suggestions
([#&#8203;17657](https://togithub.com/eslint/eslint/issues/17657)) (Josh
Goldberg ✨)

#### Chores

-
[`ba4d4d5`](https://togithub.com/eslint/eslint/commit/ba4d4d567a82554250dd8c7933322824e6a73944)
chore: remove metascraper
([#&#8203;17707](https://togithub.com/eslint/eslint/issues/17707))
(Milos Djermanovic)
-
[`0d07338`](https://togithub.com/eslint/eslint/commit/0d0733882944b4849d71a40723c251213698cef9)
chore: Update dependencies
([#&#8203;17706](https://togithub.com/eslint/eslint/issues/17706))
(Milos Djermanovic)
-
[`93256a3`](https://togithub.com/eslint/eslint/commit/93256a32e312f3f4e5c532762df71bdc06bded20)
chore: package.json update for
[@&#8203;eslint/js](https://togithub.com/eslint/js) release (ESLint
Jenkins)
-
[`485ec7d`](https://togithub.com/eslint/eslint/commit/485ec7d08ed2040c292f52bf9b9152f6c8ef4809)
test: fix ESLint tests for caching
([#&#8203;17699](https://togithub.com/eslint/eslint/issues/17699))
(Milos Djermanovic)
-
[`db06a7f`](https://togithub.com/eslint/eslint/commit/db06a7ff7992a74368f03d1f21beb00df0407021)
ci: bump actions/setup-node from 3 to 4
([#&#8203;17676](https://togithub.com/eslint/eslint/issues/17676))
(dependabot\[bot])
-
[`994596b`](https://togithub.com/eslint/eslint/commit/994596b07f5ff20a615a4be1ea03e5fd59cdb84b)
ci: run tests in Node.js 21
([#&#8203;17673](https://togithub.com/eslint/eslint/issues/17673))
(Francesco Trotta)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the
month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/sebald/pattern-analyzer).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMjcuMCIsInVwZGF0ZWRJblZlciI6IjM3LjEyNy4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>